# Generated by Django 6.0.1 on 2026-06-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blootie_app', '0004_vacio'),
        ('blootie_app', '0005_cuento'),
    ]

    operations = [
    ]
